### ISSUE TITLE
Roadmap 3.0 

### ISSUE THREAD

**Issue by tglman** [orientechnologies/orientdb#6005]
## Core
- [ ] New Profiler and Session recording
- [ ] Page compression https://github.com/orientechnologies/orientdb/issues/5383
- [x] Refactor Add Database Factory API https://github.com/orientechnologies/orientdb/issues/6011
- [ ] Remove Global Transaction Lock https://github.com/orientechnologies/orientdb/issues/6013
- [ ] 2QCache Implementation Optimization
- [x] Clean up Api and implementation for both remote+local https://github.com/orientechnologies/orientdb/issues/6011
- [x] Speed up post processing of records/vertexes https://github.com/orientechnologies/orientdb/issues/6035
- [x] NUMA-Aware Reader-Writer Locks https://github.com/orientechnologies/orientdb/issues/6037
- [ ] Synchronous WAL writes only https://github.com/orientechnologies/orientdb/issues/5956
- [x] Parallel 2-phase commit TX in the core are the basis for a more reliable and easy replication protocol
- [ ] Removing of the keys in the index. We need also to change the HASH algorithm (maybe) to have less conflicts. And the index has always to check in the record for match. But this should save a lot of space = more pages in RAM = > speed
- [ ] "Small Pages", that is much more than just smaller pages than 64Kb
- [ ] Change in the index API to help the SQL planner to take decisions. I guess it's about stats
- [ ] Incremental backup should use the WAL when present, so it would be blazing fast
- [ ] Delta sync should act like the incremental backup (=scanning all the pages) when the WAL is not present, making ALWAYS possible the delta sync between nodes
- [ ] The delta synch now fails if you changed the db structure, like you added an index/cluster/class/etc. We need to make this working, so (like above) it must be ALWAYS possible the delta sync between nodes
- [ ] Improve index scalability

## Query
- [x] New Query Engine
- [x] Simplify query API
## Binary & Remote protocol
- [ ] Serialization Optimizations https://github.com/orientechnologies/orientdb/issues/3742
- [x] Remote Push + Refactor  + Unit Tests https://github.com/orientechnologies/orientdb/issues/3496
- [ ] Merge Embedded Ridbag (optional)
- [x] Server side transaction https://github.com/orientechnologies/orientdb/issues/181
- [ ] Remote serializer negative fetch plan https://github.com/orientechnologies/orientdb/issues/3820
- [x] Paginated/Streaming of query result set https://github.com/orientechnologies/orientdb/issues/6012
## Lucene
- [x] upgrade to lucene 5.5.x or 6.x (no more filters and other things) #6069 
- [x] database level search index #5069
- [ ] index metrics for management
- [x] create functions instead of lucene operator 
## Plugins & Drivers
- [x] TinkerPop 3 https://github.com/orientechnologies/orientdb/issues/2441
- [x] JDBC: check compatibility with BI tools, implement features on demand
## ETL
- [x] refactor of parallel running #5381 
## Studio
- [x] Support for Teleporter advance mapping
- [x] Database level search index #5069

**Comment by cwaldron** [comment]
Will the extension of the clusterId to 8 bytes become part of the 3.0 roadmap?  I presume this is a major feature upgrade of the Core.

**Comment by saeedtabrizi** [comment]
@lvca , @tglman  , I thinks after adding the [ICU4J](http://site.icu-project.org/) to core of OrientDB , we can add a powerful supporting for INTL (globalization) features to core api and it can be add to this epic too . 
we can reach more performance for sorting , collation , [calendar support](https://github.com/orientechnologies/orientdb/issues/7081) , message formatting, plural word support . 
I was wondered when i sew the chart of compare [ICU collation vs Java performance](http://site.icu-project.org/charts/collation-icu4j-sun) . it can be used in orientdb version 3 family to achieve more performance . 

I hope upgrade the OrientDB with the new feature and have shiny days .

**Comment by lvca** [comment]
@saeedtabrizi +1. @luigidellaquila WDYT about using this, especially for sorting & collation?

**Comment by schernolyas** [comment]
Hi @lvca !

What about fix of rollback of transaction in 'remote' mode?

**Comment by lvca** [comment]
@schernolyas have you open an issue for that?

**Comment by schernolyas** [comment]
Hi @lvca !

Of cource! See https://github.com/orientechnologies/orientdb/issues/7133

**Comment by abhi18av** [comment]
Hi guys, 

I've been waiting for the final release of OrientDB for quite some time now but the only visible development/release is for 2.2.x releases 

I'd like to ask whether 3.x release within the scope of this year i.e. 2017 ?

**Comment by luigidellaquila** [comment]
Hi @abhi18av 

We are actively working on it, we plan to release 3.0RC1 this week, so stay tuned

Thanks

Luigi

**Comment by lightjiao** [comment]
@luigidellaquila OMG 👍

**Comment by lvca** [comment]
Hi guys,

Sorry for the delay on this. We're working hard to release v3.0-RC1 this week! Wow! And v3.0 GA is scheduled for January 2018. Yeah!

**Comment by careerscale** [comment]
This is great news. Thank you @lvca

**Comment by grexe** [comment]
wow looks like Santa/Christkind will be really busy/generous this season:=)
